[package]
name = "serenity-shuttle-bot-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
serenity = "0.12.0"
shuttle-runtime = "0.45.0"
shuttle-serenity = "0.45.0"
tokio = "1.26.0"
tracing = "0.1.37"
